language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
    sudo pip install codecov
before_script:
  - mysql -e 'create database mycollab_test;'
  - cd mycollab-deployer-community
  - mvn eclipse:eclipse
after_success:
  codecov
notifications:
  email:
    - hainguyen@esofthead.com
